[package]
name = "RustSucT4ever_lib"
version = "0.1.0"
authors = ["IljaMacht <mogutnovil@hotmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
bincode = "1.0.0"
bio = "*"
bv={version = "0.7.4", features=["serde"]} 