[package]
name = "RustSucT4ever_save_load_BP_lib"
version = "0.1.0"
authors = ["IljaMacht <mogutnovil@hotmail.com>"]

[dependencies]
serde_derive = "1.0.0"
serde = "1.0"
serde_json = "1.0"
bincode = "1.0.0"